---
- name: Ensure Git is installed
  package:
    name: git
    state: present
  tags:
    - grafana-backup

- name: Ensure Crond is installed
  package:
    name: cron
    state: present
  tags:
    - grafana-backup

- name: Install requirements for grafana backup tool
  pip:
    name:
      - requests
      - grafana-backup
    state: present
  tags:
    - grafana-backup

- name: Create backup data archive and config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ grafana_backup_archive_dir }}"
    - "{{ grafana_backup_config_dir }}"
  tags:
    - grafana-backup
    - grafana-backup-dir

- name: Update grafana backup script settings config from template
  template:
    src: grafanaSettings.json.j2
    dest: "{{ grafana_backup_config_file }}"
    force: yes
    backup: no
    owner: root
    group: root
    mode: 0755
  tags:
    - grafana-backup-settings
    - grafana-backup

- name: Creates Grafana backup Cron job
  cron:
    name: "grafana create backup"
    minute: '0'
    hour: '0'
    user: root
    job: 'grafana-backup save --config {{ grafana_backup_config_file }} && find {{ grafana_backup_archive_dir }}/ -mtime +30 -exec rm -f {} \;'
    cron_file: ansible-grafana_backup
  tags:
    - grafana-backup
    - grafana-backup-cron