---
- name: Set configuration directory path
  file:
    path: "{{ grafana_configuration_dir }}"
    state: directory
  tags:
    - grafana-configfile
    - grafana-ldap

- name: Set templatized Grafana configuration
  template:
    src: etc/grafana/grafana.ini.j2
    dest: "{{ grafana_configuration_dir }}/grafana.ini"
    force: yes
    backup: yes
    owner: "{{ grafana_config_uid }}"
    group: "{{ grafana_config_gid }}"
    mode: 0777
  when: grafana_template_configuration
  notify: |
    {% if not grafana_containerized %}
    restart grafana-server
    {% else %}
    omit
    {% endif %}
  tags:
    - grafana-configfile
- name: Set Grafana LDAP configuration
  template:
    src: etc/grafana/ldap.toml.j2
    dest: "{{ grafana_configuration_dir }}/ldap.toml"
    force: yes
    backup: yes
    owner: "{{ grafana_config_uid }}"
    group: "{{ grafana_config_gid }}"
    mode: 0777
  when: grafana_enable_auth_ldap
  notify: |
    {% if not grafana_containerized %}
    restart grafana-server
    {% else %}
    omit
    {% endif %}
  tags:
    - grafana-ldap

- name: Install grafana plugins
  grafana_plugin:
    name: "{{ item }}"
    state: present
  with_items:
    - briangann-gauge-panel
    - grafana-polystat-panel
    - grafana-piechart-panel
    - ntop-ntopng-datasource
    - vonage-status-panel
    - grafana-worldmap-panel
    - petrslavotinek-carpetplot-panel
  notify: restart grafana-server
  tags:
    - grafana-plugins
  when:
    - not grafana_containerized