---
- name: Set configuration directory path
  file:
    path: "{{ grafana_configuration_dir }}"
    state: directory
    mode: 0777
    owner: "{{ grafana_config_uid }}"
    group: "{{ grafana_config_gid }}"
    recurse: true
  tags:
    - grafana-configfile
    - grafana-ldap

- name: Set templatized Grafana configuration
  template:
    src: etc/grafana/grafana.ini.j2
    dest: "{{ grafana_configuration_dir }}/grafana.ini"
    force: yes
    backup: yes
    owner: "{{ grafana_config_uid }}"
    group: "{{ grafana_config_gid }}"
    mode: 0755
  when: grafana_template_configuration
  notify: restart grafana-server
  tags:
    - grafana-configfile

- name: Set Grafana LDAP configuration
  template:
    src: etc/grafana/ldap.toml.j2
    dest: "{{ grafana_configuration_dir }}/ldap.toml"
    force: yes
    backup: yes
    owner: "{{ grafana_config_uid }}"
    group: "{{ grafana_config_gid }}"
    mode: 0755
  when: grafana_enable_auth_ldap
  notify: restart grafana-server
  tags:
    - grafana-ldap

- name: Set grafana data directory
  file:
    path: "{{ grafana_data_dir }}"
    state: directory
    mode: 0755
    owner: "{{ grafana_config_uid }}"
    group: "{{ grafana_config_gid }}"
    recurse: true
  tags:
    - grafana-datafile
  notify: restart grafana-server


- name: Install grafana plugins
  grafana_plugin:
    name: "{{ item }}"
    state: present
    recurse: true
  with_items:
    - briangann-gauge-panel
    - grafana-polystat-panel
    - grafana-piechart-panel
    - ntop-ntopng-datasource
    - vonage-status-panel
    - grafana-worldmap-panel
    - petrslavotinek-carpetplot-panel
    - natel-discrete-panel
  notify: restart grafana-server
  tags:
    - grafana-plugins
  when:
    - not grafana_containerized