---
- name: Install any necessary dependencies [Debian/Ubuntu]
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ grafana_prereq_pkgs }}"
  when: not grafana_install_from_repo

- name: Download Grafana package via URL [Debian/Ubuntu]
  get_url:
    url: "{{ grafana_install_url }}"
    dest: /tmp/grafana-ansible-download.deb
    mode: 0644
  when: not grafana_install_from_repo

- name: Install downloaded Grafana package [Debian/Ubuntu]
  apt:
    deb: /tmp/grafana-ansible-download.deb
    state: present
  when: not grafana_install_from_repo

- name: Install APT HTTPS Transport [Debian/Ubuntu]
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: grafana_install_from_repo

- name: Import Grafana GPG signing key [Debian/Ubuntu]
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: grafana_install_from_repo

- name: Add Grafana repository [Debian/Ubuntu]
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb {{ grafana_install_release | default('stable') }} main
    state: present
  when: grafana_install_from_repo

- name: Install Grafana packages [Debian/Ubuntu]
  apt:
    name: grafana
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: grafana_install_from_repo

- name: Register, Enable, and Start Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes
    daemon_reload: yes

