---
- name: Install any necessary dependencies [Debian/Ubuntu]
  apt: 
    name: "{{ item }}" 
    state: present 
    update_cache: yes 
    cache_valid_time: 3600
  with_items:
    - python-httplib2
    - python-apt
    - curl
    - apt-transport-https
    

- name: Import Grafana GPG signing key [Debian/Ubuntu]
  apt_key:
    url: https://repos.influxdata.com/grafana.key
    state: present
  when: grafana_install_url is not defined or grafana_install_url == None

- name: Add Grafana repository [Debian/Ubuntu]
  apt_repository:
    repo: deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ grafana_install_version }}
    state: present
  when: grafana_install_url is not defined or grafana_install_url == None

- name: Install Grafana packages [Debian/Ubuntu]
  apt: 
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: grafana_install_url is not defined or grafana_install_url == None
  
- name: Download Grafana package via URL [Debian/Ubuntu]
  command: curl -o /tmp/grafana-ansible-download.deb {{ grafana_install_url }}
  when: grafana_install_url is defined and grafana_install_url != None

- name: Install downloaded Grafana package [Debian/Ubuntu]
  apt:
    deb: /tmp/grafana-ansible-download.deb
    state: present
  when: grafana_install_url is defined and grafana_install_url != None

- name: Register, Enable, and Start Grafana service
  systemd:
    name: grafana
    state: started
    enabled: yes
    daemon_reload: yes

