---
#- name: Add the OS specific varibles
#  include_tasks: install-redhat.yml
#  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

#- name: Add the OS specific varibles
#  include_tasks: install-fedora.yml
#  when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"

#- name: Add the OS specific varibles
#  include_vars: RedHat.yml
#  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"

#- name: Add the OS specific varibles
#  include_vars: Fedora.yml
#  when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"

- name: Add the OS specific varibles
  include_vars: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: Include OS specific tasks
  include_tasks: install-debian.yml
  when: ansible_os_family == "Debian"
