---
- import_tasks: install.yml
  tags: [grafana, grafana-install]

- import_tasks: configure.yml
  tags: [grafana, grafana-configure]

- import_tasks: backup.yml
  when: grafana_enable_backups
  tags: [grafana, grafana-backup]
